# Generated by Django 3.0.4 on 2020-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langdescription',
            name='selection',
            field=models.CharField(choices=[('Python', 'Python'), ('HTML', 'HTML'), ('Django', 'Django'), ('CSS', 'CSS')], default='Python', max_length=100),
        ),
    ]
