# Generated by Django 3.0.4 on 2020-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_langdescription_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='langdescription',
            name='libs',
            field=models.TextField(default='Some of libraries', help_text='name libraries'),
        ),
    ]
