# Generated by Django 3.0.4 on 2020-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_langdescription_libs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langdescription',
            name='selection',
            field=models.CharField(choices=[('Python', 'Python'), ('HTML', 'HTML'), ('Django', 'Django'), ('CSS', 'CSS')], default='HTML', max_length=100),
        ),
    ]
