# Generated by Django 3.0.4 on 2020-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200315_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langdescription',
            name='selection',
            field=models.CharField(choices=[('Python', 'Python'), ('HTML', 'HTML'), ('Django', 'Django'), ('CSS', 'CSS'), ('R', 'R'), ('bash', 'bash')], default='HTML', max_length=100),
        ),
    ]
