# Generated by Django 3.0.4 on 2020-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200322_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langdescription',
            options={'verbose_name': 'Umiejętność', 'verbose_name_plural': 'Umiejętności'},
        ),
        migrations.RemoveField(
            model_name='langdescription',
            name='selection',
        ),
        migrations.AddField(
            model_name='langdescription',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='langdescription',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
