# Generated by Django 3.0.4 on 2020-03-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LangDescription',
        ),
    ]
